language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: Qz4KrGfD5ulM10Nf5UZQiG9HpE9PQJn4oULEOEwNTUEwiIKxL0ORk70tmyKOw/QaWw7WwobgdUtgSmJSZqf4AJt/SnSeBpTIhNjxW62/9zqBV49CsW0Kxr40n8aoaj+FYlIUcGXrHTpFVaLBY1ufjkxytB+i3v4ZGgnDL2wwrKfDpd+7Qy6YDzts64FYuACfzIGxOMyhD6yO3uxve3eW3oIAVUdVPvNEN6TNEoHP3R2Jads6/lPIxL5OgyU0rcDvI7PjCxBJh3qVfaRJea6pW0D/CPJxINY7mU70fKMdJjEnfDNoAegVfbhf004CG49gp6xzv8Uf1XZezjy0Sh/bVzEbSCVXcej4NzJn2LZm8Ote5hd+X8LdHWmtmsMiSrmwlyzpktY/rSSLnAp5pcZ6sQD3mBVVMaLU+mSsuOuNNlOEv9i2r1kw1rRFq30uzgpBK7TIyeUiQ42q3+m8c+LrT+/xqoCmF4sYhGxlozKpHWo+scabXVc85/H5MSwCiSLouHl1bOUk5pZp899LmSBzE7jLDdr9GRHdooVwtj8jXJ5XXQ5UW0ttXyCLe5fv+6A3rXVy0g1ZcRcWwRt33IcONXYfa126wi6MGWAsQPbo+zO9MVZ4vL/EMJApuPRLuegv0vgbANwbHh1YJeAnIS6YV02ae3YhZ4sdfKJepbQVfAg=
  app: damico-recipes-client
  on:
    repo: miamiyankee13/damico-recipes-client
