language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: ooTEJ/dgjRiCNQkhucgH47bBapsM/81zc1SHYYS36yqxM4mB+yslFDxr9nWWLOrkHeoL6S0gRjpf1PSXRZuKPIHg9V6y8GmJ0vFPxKDsn3Uwyo9VX/RhPvwJKNh6hp+7QR4KD+EN2LUdwStgcgn8hfrEDCQM/mEeHZd33LD/oGp78nXGXIcYUMK7Y5m4TX9TOFwSB0D35Vg/vLeLyvFAPswlbZ/pVRj9KT+VHt+1i5+wI9pvAW28MhgzmRI3jUdygcVJ3FY9RKCiBb2T12aUctlZDV3aW+7nLIOLrEVoYY29dkp0YNfyXUQfK1TcC0g0bk2zNQVnEnCKF2NLogvX6PqBDbYkOPx3WPMk3/Kq08kfcWOM1U2vI2KM8BOHH4N0xhECnNACrSaI19Ryzw5ob4bRXqiImMjbuGNBpsgcu4WLy+k83lRItANOXXa3uFufXaz1/nKQBinD1YD+6oDQJunV6z7Rhd1zBww7AdWtpvRLil6aU4iB+vtrinuseScLAmhPn8/cpcxt5gHkffGRLGiv4JhNe9fmAxma8Djsl1cLDzy4POEdZIQIqs66qUXI/l3ffU2OtiiDfBs+qoiT9ckpNY44Q/vOLMkSM14nqld46zOg8u5GUDcWaF+nrs3HbaBT8ZA+ed8ssy1BTtbQc2pqEXdD8zr/ucN4i0lU0/o=
  app: damico-recipes-client
  on:
    repo: miamiyankee13/damico-recipes-client
