language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: mtuIutElWTqWD9QQiK77uTq2qnT0bTqHyp8vKJA195cD2zws/SxkZnQBdo8ciaAq1oOuxb86iKXV5Ppr0mLmrBDTDWW5t8yw37mev81YC0DFHDKUsZM2GZ5zquRWzQbIltoaIukvtmOLiPUhk/Jk09On2PPqIPVBPZKhyUfhrsmHAIqx6vt5BNcQfXYYWm2mZ8JbJL6SK5SUQgaHRGxH1zVEe65nabfGO/JK6nrkEuZV3VHY+B1YvWxoeRk+MSJZj7ru2Il2idYnPSDSAs4+Y45nGXfBv3B8XRVB4zxM4FB8ka/3ddPRoHRwz0R6DlhxOWlnjA8wYPMVMXUDr6vEm4AvQh3xu8TndnW3WoCxwlPzhEfFR035IRYQCCSsSZmZObJdkP3JqcccxfBSyJM0DpsydYR8e46O4Q3NDeNDMGUoHRAH1KJYyuulfxuwIItGsj2VYUrUaudmB5F4V3ce3QL/UC7UENLfiwXpzxHzAr2k+I5BFsDREz3Ye/+acWgK4LxUQ/kvMtT4DjggWyBbYbnTUQPpc3HrIv/mra2ojGxrMrMvQ8YhqqkwdRHlkeDcpDxzwvANzcSow4lOdj5LLQSnsG4yjPYR8WkIvWSfeo5KenJXL7dw5VbXFai+M9y8KBCjTw3g6/+/EgrJIQ9w/yAU0WO5JXcR9X9xGL2X4Hc=
  app: damico-recipes-client
  on:
    repo: miamiyankee13/damico-recipes-client
